baseURL = "https://sensical.es/"
languageCode = "en-us"
title = "Sensical SCCL"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.92.0"

[params]
  google_analytics_id=""

  [params.logo]
    mobile = "images/logo-mobile.svg"
    mobile_height = "36px"
    mobile_width = "36px"
    desktop = "images/sensical-logo.png"
    desktop_height = "29px"
    desktop_width = "217px"
    text = "snscl"
    alt = "Sensical SCCL"

  [params.homepage_meta_tags]
    meta_description = "Sensical SCCL is a developer and engineering cooperative, offering consultance services in prototyping, open science and environmental participatory processes."
    meta_og_title = "Sensical SCCL"
    meta_og_type = "website"
    meta_og_url = "https://sensical.es/"
    meta_og_image = "images/sensical-logo.png"
    meta_og_description = "Sensical SCCL is a developer and engineering cooperative, offering consultance services in prototyping, open science and environmental participatory processes."

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:contentbasename/"

[languages]
  [languages.en]
    contentDir = 'content/en'
    languageName = 'en'
    weight = 10
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = 'Work'
        pageRef = '/work'
        weight = 10
      [[languages.en.menus.main]]
        name = 'Services'
        pageRef = '/services'
        weight = 20
      [[languages.en.menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 30
  [languages.es]
    contentDir = 'content/es'
    languageName = 'es'
    weight = 20
    [languages.es.menus]
      [[languages.es.menus.main]]
        name = 'Portfolio'
        pageRef = '/work'
        weight = 10
      [[languages.es.menus.main]]
        name = 'Servicios'
        pageRef = '/services'
        weight = 20
      [[languages.es.menus.main]]
        name = 'Contacto'
        pageRef = '/contact'
        weight = 30
  [languages.cat]
    contentDir = 'content/cat'
    languageName = 'cat'
    weight = 30
    [languages.cat.menus]
      [[languages.cat.menus.main]]
        name = 'Portfolio'
        pageRef = '/work'
        weight = 10
      [[languages.cat.menus.main]]
        name = 'Serveis'
        pageRef = '/services'
        weight = 20
      [[languages.cat.menus.main]]
        name = 'Contacte'
        pageRef = '/contact'
        weight = 30
  [languages.fr]
    contentDir = 'content/fr'
    languageName = 'fr'
    weight = 40
    [languages.fr.menus]
      [[languages.fr.menus.main]]
        name = 'Travails'
        pageRef = '/work'
        weight = 10
      [[languages.fr.menus.main]]
        name = 'Services'
        pageRef = '/services'
        weight = 20
      [[languages.fr.menus.main]]
        name = 'Contact'
        pageRef = '/contact'
        weight = 30